[package]
name = "serverseeker"
version = "0.1.0"
edition = "2021"
description = "Rust wrapper for DAMcrafts Minecraft ServerSeeker API"
keywords = ["minecraft", "serverscanning"]
repository = "https://github.com/Paddyk45/serverseeker-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.18"
tokio = { version = "1.28.2", features = ["macros"] }
serde = { version = "1.0.164", features = ["derive"] }
json = "0.12.4"
exitfailure = "0.5.1"
chrono = "0.4.26"
serde_json = "1.0.96"